// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.jxl", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1735666645);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 150);
user_pref("browser.newtabpage.activity-stream.impressionId", "{28b67331-6f5d-445c-8fb4-f99b9780a8c2}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1735666647);
user_pref("browser.search.region", "BY");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1735666648");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20241224123550");
user_pref("browser.startup.homepage_override.mstone", "133.0.3");
user_pref("browser.startup.lastColdStartupCheck", 1735666648);
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"wrapper-sidebar-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"],\"zen-sidebar-top-buttons\":[\"zen-sidepanel-button\"],\"zen-sidebar-icons-wrapper\":[\"zen-profile-button\",\"zen-workspaces-button\",\"downloads-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"zen-sidebar-icons-wrapper\",\"PersonalToolbar\"],\"currentVersion\":20,\"newElementCount\":2}");
user_pref("distribution.iniFile.exists.appversion", "1.0.2-b.5");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.home-region", "BY");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.formautofill.creditCards.reauth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECO6wa63pYZFBBAj0dsJ4xctVIQ==");
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20241224123550");
user_pref("extensions.lastAppVersion", "1.0.2-b.5");
user_pref("extensions.lastPlatformVersion", "133.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"e6f57f80-8a6f-4f2a-8d59-c68fb60f9635\",\"pictureinpicture@mozilla.org\":\"5c00cabf-a71e-408f-9dd9-f6b3e03fd884\",\"screenshots@mozilla.org\":\"768e80cd-64bd-491a-8df2-a58df3657ab9\",\"webcompat-reporter@mozilla.org\":\"b59ecc97-273b-42d7-a610-8c587cbe7780\",\"webcompat@mozilla.org\":\"9a9ec78c-2c11-40e8-8609-534481143987\",\"firefox-compact-dark@mozilla.org\":\"2898181a-7501-4902-9954-c79879e9a842\",\"addons-search-detection@mozilla.com\":\"0d3e3ed4-40a1-46e2-99e3-8ae3968970f9\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx.blacklist.accelerated-canvas2d", 3);
user_pref("gfx.blacklist.accelerated-canvas2d.failureid", "FEATURE_FAILURE_DL_BLOCKLIST_NO_ID");
user_pref("gfx.blacklist.dmabuf", 4);
user_pref("gfx.blacklist.dmabuf.failureid", "FEATURE_FAILURE_DL_BLOCKLIST_NO_ID");
user_pref("gfx.blacklist.gl.threadsafe", 4);
user_pref("gfx.blacklist.gl.threadsafe.failureid", "FEATURE_FAILURE_DL_BLOCKLIST_NO_ID");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.globalprivacycontrol.was_ever_enabled", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs2", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("sidebar.backupState", "{\"width\":\"\",\"command\":\"\"}");
user_pref("signon.management.page.os-auth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECMM1hw2EBRepBAiCux9iwnmsUw==");
user_pref("toolkit.startup.last_success", 1735666641);
user_pref("toolkit.telemetry.cachedClientID", "e9df3966-45fa-46e2-98ed-1107ee1308b9");
user_pref("toolkit.telemetry.cachedProfileGroupID", "483e55f6-6d8e-497f-ab7c-fe2eb4079c91");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("zen.keyboard.shortcuts.version", 6);
user_pref("zen.workspaces.active", "4382f26f-cab5-4698-a2b6-a33e03f221fb");
